apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  supabase-url: aHR0cHM6Ly94dG9pcHZhaWhsZWxsb3B3dGh5Zi5zdXBhYmFzZS5jbw==
  supabase-key: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5oMGIybHdkbUZwYUd4bGJHeHZjSGQwYUhsbUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTkRrM01qYzBORFlzSW1WNGNDSTZNakEyTlRNd016UTBObjAuYmlxT2hEWU5JTUZFYWctODdZSkNGNW1zZFpkSEpzbF8zWDNRdThnR3BHbw==