name: Multi-Channel Publishing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build Android
        run: |
          cd android
          ./gradlew assembleDebug
          
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          
      - name: Build iOS
        run: |
          cd ios
          pod install
          xcodebuild -workspace TestClaudeCursorApp.xcworkspace -scheme TestClaudeCursorApp -configuration Debug -sdk iphonesimulator

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment"
          # Add your staging deployment commands here
          
      - name: Deploy to production
        if: success()
        run: |
          echo "Deploying to production environment"
          # Add your production deployment commands here 