name: Multi-Channel Publishing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  backend-unit-test:
    runs-on: ubuntu-latest
    environment:
      name: testing
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          
      - name: Run Backend Unit Tests
        run: |
          cd backend
          mvn clean test -Dtest="**/AuthControllerUnitTest,**/HelloControllerTest"

  backend-integration-test:
    runs-on: ubuntu-latest
    environment:
      name: testing
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          
      - name: Run Backend Integration Tests
        run: |
          cd backend
          mvn clean test -Dtest="**/integration/**"

  frontend-test:
    runs-on: ubuntu-latest
    environment:
      name: testing
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/TestClaudeCursorApp/package-lock.json'
          
      - name: Install Frontend Dependencies
        run: |
          cd frontend/TestClaudeCursorApp
          npm ci
          
      - name: Run Frontend Linting
        run: |
          cd frontend/TestClaudeCursorApp
          npm run lint
          
      - name: Run Frontend Tests
        run: |
          cd frontend/TestClaudeCursorApp
          npm test -- --watchAll=false --coverage=false

  android-build:
    needs: [backend-unit-test, backend-integration-test, frontend-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/TestClaudeCursorApp/package-lock.json'
          
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
          
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Install Frontend Dependencies
        run: |
          cd frontend/TestClaudeCursorApp
          npm ci
          
      - name: Build Android
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
          build-root-directory: frontend/TestClaudeCursorApp/android
          gradle-version: 8.13

  ios-build:
    needs: [backend-unit-test, backend-integration-test, frontend-test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/TestClaudeCursorApp/package-lock.json'
          
      - name: Install Frontend Dependencies
        run: |
          cd frontend/TestClaudeCursorApp
          npm ci
          
      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: frontend/TestClaudeCursorApp/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
            
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          
      - name: Build iOS
        run: |
          cd frontend/TestClaudeCursorApp/ios
          pod install
          xcodebuild -workspace TestClaudeCursorApp.xcworkspace -scheme TestClaudeCursorApp -configuration Debug -sdk iphonesimulator

  deploy:
    needs: [android-build, ios-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to AWS EC2
        run: |
          echo "🚀 Deploying to AWS EC2..."
          
          # Create app directory on server
          ssh -i ~/.ssh/ec2-key.pem ec2-user@${{ secrets.EC2_HOST }} "mkdir -p /home/ec2-user/app"
          
          # Copy source code (excluding build artifacts)
          rsync -avz --progress -e "ssh -i ~/.ssh/ec2-key.pem" \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude 'target' \
            --exclude '.DS_Store' \
            --exclude '*.log' \
            --exclude 'android/.gradle' \
            --exclude 'android/app/.cxx' \
            --exclude 'android/app/build' \
            --exclude 'ios/build' \
            --exclude '*.apk' \
            ./backend ./frontend ./docker-compose.prod.yml \
            ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/
          
          # Build and deploy containers
          ssh -i ~/.ssh/ec2-key.pem ec2-user@${{ secrets.EC2_HOST }} \
            "cd /home/ec2-user/app && \
             docker-compose -f docker-compose.prod.yml down && \
             docker-compose -f docker-compose.prod.yml build backend && \
             docker-compose -f docker-compose.prod.yml up -d backend"
          
          # Verify deployment
          echo "✅ Checking deployment status..."
          ssh -i ~/.ssh/ec2-key.pem ec2-user@${{ secrets.EC2_HOST }} \
            "cd /home/ec2-user/app && docker-compose -f docker-compose.prod.yml ps"
          
      - name: Health Check
        run: |
          echo "🏥 Performing health check..."
          sleep 30
          
          # Check if backend is healthy via load balancer
          if curl -f http://testclaudecursor-alb-1183948507.us-east-1.elb.amazonaws.com/hello; then
            echo "✅ Health check passed!"
          else
            echo "❌ Health check failed!"
            exit 1
          fi
          
      - name: Deployment Summary
        if: success()
        run: |
          echo "🎉 Deployment successful!"
          echo "🌐 Backend API: http://testclaudecursor-alb-1183948507.us-east-1.elb.amazonaws.com"
          echo "📱 Endpoints available:"
          echo "  - GET /hello"
          echo "  - POST /auth/login" 